### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by monza258** [jacopo-j/testflight-watcher#1]
Hi,
thanks for this script.
I will use it but I get an error a first time. 

```
pi@raspberrypi:~/testflight-watcher $ ./telegram_bot.py u6iogfd0,
Traceback (most recent call last):
  File "./telegram_bot.py", line 28, in <module>
    testflight_watcher.watch(sys.argv[-1].split(","), send_notification)
  File "/home/pi/testflight-watcher/testflight_watcher.py", line 25, in watch
    free_slots = (page.xpath(XPATH_STATUS)[0] != FULL_TEXT)
IndexError: list index out of range
```  

Do you know what a about wrong?

**Comment by jacopo-j** [comment]
I haven't maintained this script for a while, so the page parser is probably just outdated. I may look into it if I have time in the future, but I haven't used the script for a while so no promises. PRs are welcome

**Comment by monza258** [comment]
Hope for it. Thanks for the fast respond

**Comment by monza258** [comment]
> I haven't maintained this script for a while, so the page parser is probably just outdated. I may look into it if I have time in the future, but I haven't used the script for a while so no promises. PRs are welcome

Hi, any news about it?

**Comment by raymand211092** [comment]
> Hi,
> thanks for this script.
> I will use it but I get an error a first time.
> 
> ```
> pi@raspberrypi:~/testflight-watcher $ ./telegram_bot.py u6iogfd0,
> Traceback (most recent call last):
>   File "./telegram_bot.py", line 28, in <module>
>     testflight_watcher.watch(sys.argv[-1].split(","), send_notification)
>   File "/home/pi/testflight-watcher/testflight_watcher.py", line 25, in watch
>     free_slots = (page.xpath(XPATH_STATUS)[0] != FULL_TEXT)
> IndexError: list index out of range
> ```
> 
> Do you know what a about wrong?

Hello, how do I make the notifications work when they run out?

**Comment by raymand211092** [comment]
> I haven't maintained this script for a while, so the page parser is probably just outdated. I may look into it if I have time in the future, but I haven't used the script for a while so no promises. PRs are welcome

Hello, how do I make the notifications work when they run out?

**Comment by VCTGomes** [comment]
Is it working yet? I'm trying to create this bot, but it didn't worked here
